//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopitalCsTool.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("csh@radnet.kr")]
        public string gmailid {
            get {
                return ((string)(this["gmailid"]));
            }
            set {
                this["gmailid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1q2w3e4r1!")]
        public string gmailpw {
            get {
                return ((string)(this["gmailpw"]));
            }
            set {
                this["gmailpw"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("os1005")]
        public string nccvpnid {
            get {
                return ((string)(this["nccvpnid"]));
            }
            set {
                this["nccvpnid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1234$!@#qwe")]
        public string nccvpnpw {
            get {
                return ((string)(this["nccvpnpw"]));
            }
            set {
                this["nccvpnpw"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\downloadedFiles\\\\")]
        public string zolvuezippath {
            get {
                return ((string)(this["zolvuezippath"]));
            }
            set {
                this["zolvuezippath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"@echo off

>nul 2>&1 ""%SYSTEMROOT%\system32\cacls.exe"" ""%SYSTEMROOT%\system32\config\system""

if '%errorlevel%' NEQ '0' (

    echo 관리 권한을 요청 ...

    goto UACPrompt

) else ( goto gotAdmin )

:UACPrompt

    echo Set UAC = CreateObject^(""Shell.Application""^) > ""%temp%\getadmin.vbs""

    set params = %*:""=""""

    echo UAC.ShellExecute ""cmd.exe"", ""/c %~s0 %params%"", """", ""runas"", 1 >> ""%temp%\getadmin.vbs""



    ""%temp%\getadmin.vbs""

    rem del ""%temp%\getadmin.vbs""

    exit /B



:gotAdmin

c:\progra~1\intern~1\iexplore.exe https://www.onpacs.com/Login.aspx")]
        public string onpacsshotcut {
            get {
                return ((string)(this["onpacsshotcut"]));
            }
            set {
                this["onpacsshotcut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\downloadedFiles\\OptimumInstaller.exe")]
        public string cv3path {
            get {
                return ((string)(this["cv3path"]));
            }
            set {
                this["cv3path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\FILEDATA")]
        public string BRHCopypath {
            get {
                return ((string)(this["BRHCopypath"]));
            }
            set {
                this["BRHCopypath"] = value;
            }
        }
    }
}
